### ISSUE TITLE
Trouble spying on recursive function

### ISSUE THREAD

**Issue by nicinabox** [jupiter/simple-mock#14]
I'm having trouble figuring out how to spy on a recursive function. The call to `tryFetch` in the exported method seems to be a call to the original. The first call from my test is stubbed correctly. I couldn't find anything in the docs referencing recursive calls from imports. This is also run through babel using the mocha compiler flag.

Here are the relevant parts my setup:

```javascript
// test
import fetch from 'node-fetch'
import simple from 'simple-mock'
import * as api from '../../src/utils/api'

it('retries failed requests', () => {
  var stubbedFetch = global.fetch = simple.stub(fetch)
    .rejectWith(new TypeError('Network request failed'))

  var tryFetchSpy = simple.mock(api.tryFetch)

  return tryFetchSpy('http://example.com')
    .catch(() => {
      // tryFetchSpy.callCount always equals 1, but the original method IS called 6 times.
      expect(tryFetchSpy.callCount, 'to equal', 6) 
    })
})
```

```javascript
// ../../src/utils/api
export function tryFetch(url, options, retryInterval = 500, maxRetries = MAX_RETRIES) {
  return fetch(url, options)
    .then(checkStatus)
    .then(toJSON)
    .catch((err) => {
      if (didNetworkRequestFail(err)) {
        if (maxRetries > 0) {
          // This call to tryFetch calls the original, but I want the spy in my test.
          return tryFetch(url, options, retryInterval * 2, maxRetries - 1)
        }
      }

      return handleError(err)
    })
}
```

**Comment by jupiter** [comment]
Change `simple.mock(api.tryFetch)` to `simple.mock(api, 'tryFetch')`

**Comment by nicinabox** [comment]
@jupiter Thanks for replying. I've also tried `simple.mock(api, 'tryFetch')` but the result is the same.

<img width="728" alt="screen shot 2016-05-21 at 3 01 42 pm" src="https://cloud.githubusercontent.com/assets/246280/15450591/0cc27a4a-1f65-11e6-8e13-321deacc2aee.png">

**Comment by jupiter** [comment]
I just ran the code with missing methods mocked out and I got error `expected 7 to equal 6`, which I suppose is correct. However, I noticed you are using Babel, which means that you'd need to call the recursive 'tryFetch' on the module you are mocking it on. E.g. either:

```
import * as api from './api';
...
return api.tryFetch(url, options, retryInterval * 2, maxRetries - 1)
```

Or just:

```
return exports.tryFetch(url, options, retryInterval * 2, maxRetries - 1)
```

**Comment by nicinabox** [comment]
💥 Calling with `exports` in the recursive method did it. I didn't even think to do that. You're the man @jupiter 👍 Thanks for you're help.
