### ISSUE TITLE
Convert stub.loop to a function

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [jupiter/simple-mock#15]
Stub methods chain be chained since they return the stub object. However, **stub.loop** is not a function but a variable. Consider changing it to a function (I can look into implementing the change if you find this reasonable).
# Examples
## Variable

``` js
var stub = simple.stub().returnWith('bar');
mock = {
  foo: stub
};

stub.loop = false;
```
## Function

``` js
var mock = {
  foo: simple.stub().loop(false).returnWith('bar')
};
```

**Comment by HCanber** [comment]
Changing it would be a breaking change, so it's probably better to add new functions that can be chained. What about something like:
`stub.noLoop()` equals `stub.loop = false`
`stub.withLoop()` equals `stub.loop = true`
