### ISSUE TITLE
simple-chai not published on npm

### ISSUE THREAD

**Issue by codyzu** [jupiter/simple-mock#18]
First, thanks for this library, we use it a lot!

I recently tried to use https://github.com/jupiter/simple-mock-chai because we already use chai and I am converting some sinon tests to simple-mock. However, there are 2 issues:
1. simple-chai does not seem to be published on npm :-(
2. jupiter/simple-mock-chai does not allow creating issues on that repo (maybe because it's a fork, [see here on stackexchange](http://programmers.stackexchange.com/a/179470).

Is simple-chai still a thing?

Thanks!

**Comment by codyzu** [comment]
ping @jupiter

**Comment by jupiter** [comment]
Sorry, I haven't completed simple-mock for chai. I should hide this repo. However, you're welcome to help out if you like. 

I'm not actually a huge fan of chai, for the same reason I created simple-mock: too much sugar creates more mental overhead, not less.

**Comment by codyzu** [comment]
@jupiter I agree with your point and I'm not a big fan of chai either... however we use chai and simple-mock in a big project and that's why I found simple-mock-chai. No worries and unfortunately I probably won't being making an PR's in the near future. I'll spread the word on my team and see if there's any interest from any else...
