### ISSUE TITLE
Mocking simple function not working as expected

### ISSUE THREAD

**Issue by arb** [jupiter/simple-mock#25]
```
const mockTarget = () => {
  console.log('mockTarget has been called')
}

const handler = () => mockTarget();

simple.mock(mockTarget).returnWith(undefined);

handler();
```

In this example, I would expect `mockTarget` to not be called, but it is when using simple-mock@0.7.3. Is this expected, am I using it wrong, or a 🐛 ?

**Comment by HCanber** [comment]
`simple.mock` (and `simple.spy`) used on function as in your example creates a standalone stub/spy, see https://github.com/jupiter/simple-mock#standalone-stubs-and-spies

so you have to called the returned function.

```js
const fn = simple.mock(mockTarget).returnWith(undefined);
fn();
```

Or, you can replace functions on objects, so this will also work:

```js
const o = { mockTarget }
const handler = () => o.mockTarget();

simple.mock(o, 'mockTarget').returnWith(undefined);

handler();
```
