### ISSUE TITLE
Thank you 🎁

### ISSUE THREAD

**Issue by gr2m** [jupiter/simple-mock#27]
Hey Pieter,

just want to say thanks. I love the `simple-mock` library. I use it in a lot of my projects and it never let me down. I think it’s super robust and honestly I don’t see a reason not to release a `1.0.0` :) 

If there is anything I can help out with feel free to ping me directly

That’s all, have a great weekend 😁

**Comment by jupiter** [comment]
Hey, thanks! That's great to hear.
