### ISSUE TITLE
How to mock a function?

### ISSUE THREAD

**Issue by frankli-dev** [jupiter/simple-mock#32]
```
   const convert = require('pngtojpg');
   ... 
   const result = await convert();
```

How can I mock convert?
`simple.mock(convert).resultWith()` or `simple.mock(convert, 'call').resultWith()`, neither is working

Please help me
Thanks in advance

**Comment by true-eye** [comment]
Any update, please?

I also have an issue when mocking `fetch` function.

```
const fetch = request('node-fetch');
...
const url = `https://example.com/api`
const response = await fetch(url);
```

How can I mock this request?

I've tried the following ways but nothing works
```
simple.mock(fetch).resolveWith("{}");
simple.mock(fetch, 'default').resolveWith("{}");
```

Please help me

**Comment by frankli-dev** [comment]
Any update?

I also have an issue when mocking `fetch` function.

```
const fetch = request('node-fetch');
...
const url = `https://example.com/api`
const response = await fetch(url);
```

How can I mock this request?

I've tried the following ways but nothing works
```
simple.mock(fetch).resolveWith("{}");
simple.mock(fetch, 'default').resolveWith("{}");
```

**Comment by jupiter** [comment]
Hi, 

As node-fetch exports a function as the module, you'd need to change the way you use it. It may not be ideal, but this is how you'd do it:

```js
const fetch = request('node-fetch');
const url = `https://example.com/api`
const response = await fetch.default(url);
```

And mocking like this:

```
simple.mock(fetch, 'default').resolveWith("{}");
```

**Comment by jupiter** [comment]
For 'png-to-jpg' you might want to look to a module such as https://www.npmjs.com/package/mock-require

**Comment by true-eye** [comment]
Thank you for sharing that!
