### ISSUE TITLE
Not working with destructured objects

### ISSUE THREAD

**Issue by tejohnso** [jupiter/simple-mock#33]
When using object destructuring on the require object, the mock doesn't work. I'm not sure this is fixable as there is no longer a reference to a mocked object property during test runtime. 

Test
```
const simple = require("simple-mock");
const module = require("module.js");
const target = require("target.js");

simple.mock(module, "functionToBeMocked").returnWith(true);
target.targetFn()
```

Code Under Test in target.js (NOT working with destructuring on first line)
```
const {functionToBeMocked} = require("module.js");

function targetFn {
  functionToBeMocked() // calls real functionToBeMocked from module.js instead of returning with true as mocked
}
```

Code Under Test in target.js (Works without destructuring)
```
const module = require("module.js");

function targetFn {
  module.functionToBeMocked() // calls real functionToBeMocked from module.js instead of returning with true as mocked
}
```

**Comment by jupiter** [comment]
Yes, the destructuring happens at module load time, which is before the mocking happens. Had the destructuring been inside the function, it would happen at run time, which should be after mocking.

**Comment by tejohnso** [comment]
Yeah. It would be nice to be able to use destructuring at module load time while still being able to mock. But I'll just go ahead and  close this :)
